# config.py
# US Pullback Scanner Configuration

# 摆动窗口（局部极值检测）
SWING_WINDOW = 3

# 趋势线回溯长度
SHORT_TREND_LOOKBACK = 30
LONG_TREND_LOOKBACK = 90
LONG_TERM_TREND_BONUS = 5

# 双底/双顶结构最小间隔
MIN_DOUBLE_STRUCTURE_GAP = 20
DOUBLE_STRUCTURE_WIDE_GAP_BONUS = 5
DOUBLE_STRUCTURE_WIDE_GAP_THRESHOLD = 60

# 方向过滤参数（变为加分项）
DIRECTION_FILTER_DAYS = 5
DIRECTION_FILTER_MIN_PCT = 1.0
MIN_CLOSE_POSITION_PCT = 0.40   # 收盘价在当日高低区的位置阈值

# 52周高低位接近度
WEEK52_PROXIMITY_BONUS_MAX = 15
WEEK52_LOOKBACK = 252

# 20日均线过滤（硬条件）
PULLBACK_20D_FILTER = True

# 确认日距今最大允许天数（避免信号过时）
PULLBACK_MAX_CONFIRM_AGE_DAYS = 90

# 流动性门槛
MIN_AVG_DOLLAR_VOLUME_20D = 20_000_000
LIQUIDITY_BAND_HIGH = 50_000_000

# 下载参数
STAGE1_BATCH = 120
STAGE2_BATCH = 100
DOWNLOAD_TIMEOUT = 45
RETRY_COUNT = 3